DROP DATABASE IF EXISTS play;

CREATE DATABASE play;

GRANT ALL PRIVILEGES ON playc.* to adminAEEWrfL@localhost IDENTIFIED BY 'Tya597USndYs';

USE play;

CREATE TABLE IF NOT EXISTS registeredUsers (
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(256) NOT NULL,
	password VARCHAR(256) NOT NULL,
	name VARCHAR(256) NOT NULL,
	PRIMARY KEY(id)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS profiles (
	id INT NOT NULL,
	about VARCHAR(10000),
	musicInterest VARCHAR(10000),
	imgpath VARCHAR(256),
	PRIMARY KEY (id)
)ENGINE=InnoDB;

